export default {
  defaultSidebar: [
    'intro',
    {
      type: 'category',
      label: '快速开始',
      collapsible: true,
      items: [
        'getting-started/introduction',
        'getting-started/installation',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: '功能说明',
      collapsible: true,
      items: [
        'features/intro',
        {
          type: 'category',
          label: '数据管理',
          collapsible: true,
          items: [
            'features/data-management/intro',
            'features/data-management/file-formats',
            'features/data-management/import-export',
            'features/data-management/project-files',
          ],
        },
        {
          type: 'category',
          label: '可视化',
          collapsible: true,
          items: [
            'features/visualization/intro',
            'features/visualization/view-controls',
            'features/visualization/color-modes',
            'features/visualization/display-settings',
          ],
        },
        {
          type: 'category',
          label: '滤波处理',
          collapsible: true,
          items: [
            'features/filtering/intro',
            'features/filtering/passthrough',
            'features/filtering/voxel-grid',
            'features/filtering/statistical-outlier',
            'features/filtering/radius-outlier',
            'features/filtering/conditional',
            'features/filtering/grid-minimum',
            'features/filtering/local-maximum',
          ],
        },
        {
          type: 'category',
          label: '配准',
          collapsible: true,
          items: [
            'features/registration/intro',
            'features/registration/align-by-centers',
            'features/registration/global-registration',
            'features/registration/fine-registration',
            'features/registration/point-pairs',
          ],
        },
        {
          type: 'category',
          label: '分割',
          collapsible: true,
          items: [
            'features/segmentation/intro',
            'features/segmentation/shape-detection',
            'features/segmentation/morphological',
            'features/segmentation/region-growing',
            'features/segmentation/clustering',
            'features/segmentation/supervoxel',
          ],
        },
        'features/ground-segmentation/intro',
        'features/vegetation/intro',
        {
          type: 'category',
          label: '变化检测',
          collapsible: true,
          items: [
            'features/change-detection/intro',
            'features/change-detection/cloud-to-cloud',
            'features/change-detection/cloud-to-mesh',
            'features/change-detection/scalar-bar',
          ],
        },
        {
          type: 'category',
          label: '曲面重建与网格',
          collapsible: true,
          items: [
            'features/surface/intro',
            'features/surface/reconstruction',
            'features/surface/convex-hull',
            'features/surface/boundary',
          ],
        },
        'features/distance/intro',
        {
          type: 'category',
          label: '编辑工具',
          collapsible: true,
          items: [
            'features/editing/intro',
            'features/editing/colors',
            'features/editing/transformation',
            'features/editing/normals',
            'features/editing/scale',
            'features/editing/bounding-box',
          ],
        },
        'features/measure/intro',
        'features/range-image/intro',
      ],
    },
    {
      type: 'category',
      label: '教程',
      collapsible: true,
      items: [
        'tutorials/intro',
        'tutorials/basic-workflow',
        'tutorials/ground-filtering',
        'tutorials/registration-tutorial',
        'tutorials/change-detect-tutorial',
        'tutorials/python-automation',
      ],
    },
    {
      type: 'category',
      label: '进阶与开发',
      collapsible: true,
      items: [
        'advanced/intro',
        'advanced/large-pointcloud',
        'advanced/global-shift',
        {
          type: 'category',
          label: 'Python 脚本',
          collapsible: true,
          items: [
            'advanced/python-scripting/intro',
            'advanced/python-scripting/console',
            'advanced/python-scripting/editor',
            'advanced/python-scripting/api-reference',
          ],
        },
        'advanced/plugin-development/intro',
        {
          type: 'category',
          label: '开发指南',
          collapsible: true,
          items: [
            'development/intro',
            'development/build',
            'development/architecture',
            'development/adding-algorithm',
            'development/adding-file-format',
            'development/extending-python',
            'development/faq',
          ],
        },
      ],
    },
  ],
};
